name: Service Provisioning

on:
  workflow_dispatch:
    inputs:
      context:
        type: string
        description: nullplatform service lifecycle workflow context
        required: true

permissions:
  id-token: write
  contents: read
  packages: read
  actions: write

jobs:
  process-notification:
    runs-on: ubuntu-latest
    outputs:
      formatted_input: ${{ steps.parse-notification.outputs.formatted_input }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse Notification
        id: parse-notification
        env:
          NOTIFICATION_PAYLOAD: ${{ inputs.context }}
        run: |
          echo "Received Notification with Payload"
          echo "$NOTIFICATION_PAYLOAD"
          FORMATTED_INPUT=$(echo "$NOTIFICATION_PAYLOAD" | echo $NOTIFICATION_PAYLOAD | jq -c '(.notification.service.dimensions) * (.notification.service.attributes) * (.notification.link?.attributes // {}) * (.notification.parameters)')
          echo "formatted_input=${FORMATTED_INPUT}" >> $GITHUB_OUTPUT

  worker:
    needs: process-notification
    uses: nullplatform/examples-services-import-terraform-workflow/.github/workflows/worker.yml@main
    with:
      notification: ${{ needs.process-notification.outputs.formatted_input }}

  update-status:
    needs: worker
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Install nullplatform cli
        run: curl https://cli.nullplatform.com/install.sh | sh
      - name: Update Entity Status
        env:
          NULLPLATFORM_API_KEY: ${{ secrets.NULLPLATFORM_API_KEY }}
          NOTIFICATION_PAYLOAD: ${{ inputs.context }}
        run: |
          STATUS=${{ contains(fromJSON('["failure", "cancelled"]'), needs.worker.result) && 'failed' || 'success' }}

          echo "Workcall status is $STATUS"

          export LINK_ID=$(echo $NOTIFICATION_PAYLOAD | jq -r .notification.link.id)
          export SERVICE_ID=$(echo $NOTIFICATION_PAYLOAD | jq -r .notification.service.id)

          echo "LINK_ID is $LINK_ID"
          echo "SERVICE_ID is $SERVICE_ID"

          if [[ $LINK_ID ]]; then
            np link action update --status ${{ contains(fromJSON('["failure", "cancelled"]'), job.status) && 'failed' || 'success' }} --messages '[]' --results '{}'
          elif [[ $SERVICE_ID ]]; then
            np service action update --status ${{ contains(fromJSON('["failure", "cancelled"]'), job.status) && 'failed' || 'success' }} --messages '[]' --results '{}'
          fi
